---
name: Build

on:
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - "**.md"
      - "LICENSE"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: linux, value: ubuntu-latest }
          - { name: darwin, value: macos-latest }
        arch:
          - amd64
          - arm64
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Build for ${{ matrix.os.name }}-${{ matrix.arch }}
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          if [[ "${{ matrix.os.name }}" == "darwin" ]] && [[ "${{ matrix.arch }}" == "arm64" ]]; then
            export CGO_ENABLED=1
          fi
          make build
